name: ContainerAction
description: Calculator to test the container action
inputs:
  number1: 
    default: 0
    required: true
  number2:
    default: 0
    required: true
outputs:
  result:
    description: 'output of the sum of 2 numbers'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.number1}}
    - ${{inputs.number2}}
    
